### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by xXSirGamesXx** [xXSirGamesXx/CommandCharger#2]
- [ ] /cc help

- [ ] /cc <add> [cmd]

- [ ] /cc del [cmd]

- [ ] /cc list [cmd]

- [ ] /cc info

**Comment by draco123493** [comment]
Hello can you help me? When i use this, it crashes my server and it won't start, i use PMMP and EconomyAPI. Please reply ASAP

**Comment by xXSirGamesXx** [comment]
The plugin isnt fully made, i haven't really added much. So it wont work.

**Comment by draco123493** [comment]
May i know when it will fully work?

**Comment by xXSirGamesXx** [comment]
Yes but im not sure when i'll get to it.
